### ISSUE TITLE
RRD tools

### ISSUE THREAD

**Issue by ghost** [ProHill/ADS-B-Stuff#1]
I have tried to setup the rrd tools graphs for my pi aware receiver on another machine. I think I have edited the neccesary parts of the files to suit my setup. When I run the make-graphs.sh script, I get:
`ERROR: opening '/var/lib/collectd/rrd/PiAware/dump1090-rpi/dump1090_aircraft-recent.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/PiAware/dump1090-rpi/dump1090_cpu-demod.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/PiAware/dump1090-rpi/dump1090_tracks-all.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/PiAware/table-rpi/gauge-cpu_temp.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/PiAware/dump1090-rpi/dump1090_range-max_range.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/PiAware/dump1090-rpi/dump1090_messages-local_accepted.rrd': No such file or directory`
No files are being created in /var/lib/collectd/rrd/PiAware when I run the script.

**Comment by ProHill** [comment]
Check /var/lib/collectd and see if there is anything in there - make sure you have the right directory, and remember it is case sensitive.

**Comment by ghost** [comment]
In /var/lib/collectd there is a directory called 'rrd'. Inside that is only a directory with the name of my ubuntu machine's hostname that I am running the scripts on. There is no 'piaware' directory

**Comment by ProHill** [comment]
You have something misconfigured in your collectd.conf. Make sure you are putting it in the right place. Depending on your distribution it may be /etc/collectd or just right in /etc.
